# This file was generated by GoReleaser. DO NOT EDIT.
class CfRoutingSuite < Formula
  desc "A suite containing (server) and client for challenging the cloud foundry routing tier."
  homepage "https://github.com/sklevenz/cf-routing-suite/"
  url "https://github.com/sklevenz/cf-routing-suite/releases/download/0.1.1/cf-routing-suite_0.1.1_macOS_64-bit.tar.gz"
  version "0.1.1"
  sha256 "7e90de86bfd24e3c59711b95fdf90f2935f98e127d2048b6e63885fedd5ae82e"

  def install
    bin.install "cfrs-client"
  end

  test do
    system "#{bin}/cf-routing-suite/client/cfrs-client -version"
  end
end
