# This file was generated by GoReleaser. DO NOT EDIT.
class Terraformer < Formula
  desc "A go program that generates terraform using go templates ..."
  homepage "https://github.com/sklevenz/terraformer"
  url "https://github.com/sklevenz/terraformer/releases/download/1.0.3/terraformer_1.0.3_Darwin_x86_64.tar.gz"
  version "1.0.3"
  sha256 "3980cdece529f3daa5397a404a52152db2d9a3d17aea46f5682546398fe2b448"

  def install
    bin.install "terraformer"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
