# This file was generated by GoReleaser. DO NOT EDIT.
class Terraformer < Formula
  desc "A go program that generates terraform using go templates ..."
  homepage "https://github.com/sklevenz/terraformer"
  url "https://github.com/sklevenz/terraformer/releases/download/1.0.0/terraformer_1.0.0_Darwin_x86_64.tar.gz"
  version "1.0.0"
  sha256 "20750155fb6fff8ba2bdf43ca3e837d6dae9828ec873a60a78b7c4a6010db3a3"

  def install
    bin.install "terraformer"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
