# This file was generated by GoReleaser. DO NOT EDIT.
class Terraformer < Formula
  desc "A go program that generates terraform using go templates ..."
  homepage "https://github.com/sklevenz/terraformer"
  url "https://github.com/sklevenz/terraformer/releases/download/1.0.1/terraformer_1.0.1_Darwin_x86_64.tar.gz"
  version "1.0.1"
  sha256 "7055278cca7285b617c9c1c3407148cb9c0123f5e6dfae4b4b04d89b1c65ba0c"

  def install
    bin.install "terraformer"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
